name: PowerShell code scan

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze:
    name: Analyze
    uses: PolicyVault/.github/.github/workflows/powershell-code-scan.yml@cfd4cdda5f372298a1dc38ebb8fceb0697c4718b
